ALTER TYPE "LifeCoinItemType" ADD VALUE IF NOT EXISTS 'STREAK_EFFECT';
ALTER TYPE "LifeCoinItemType" ADD VALUE IF NOT EXISTS 'ACHIEVEMENT_DECORATION';
ALTER TYPE "LifeCoinItemType" ADD VALUE IF NOT EXISTS 'PROFILE_THEME';
ALTER TYPE "LifeCoinItemType" ADD VALUE IF NOT EXISTS 'SPECIAL';
