"use client";

import { useState } from "react";
import { Bell, Check, Circle, Plus, Target, Trash2 } from "lucide-react";

import { completeGoal, createGoal, createReminder, deleteGoal, deleteReminder, getPlanningData, toggleReminder } from "@/actions/planning.actions";
import type { PlanningData } from "@/types/planning-dashboard";

function today() { return new Date().toISOString().slice(0, 10); }

export function PlanningDashboard({ initialData, todayValue, includeHabits = false, mode = "goals" }: { initialData: PlanningData; todayValue?: string; includeHabits?: boolean; mode?: "goals" | "reminders" }) {
  const [data, setData] = useState(initialData); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  async function refresh() { setData(await getPlanningData(includeHabits)); }
  async function run(task: () => Promise<void>, message: string) { setBusy(true); setError(""); setNotice(""); try { await task(); await refresh(); setNotice(message); } catch (caught) { setError(caught instanceof Error ? caught.message : "Action failed."); } finally { setBusy(false); } }
  const isGoals = mode === "goals";
  return <main className="mx-auto max-w-375 px-5 pb-12 pt-7 sm:px-8 lg:px-10"><div className="mb-7"><p className="eyebrow text-cyan-300">{isGoals ? "Personal progress" : "Timely signals"}</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-white sm:text-4xl">{isGoals ? "Goals" : "Reminders"}</h1><p className="mt-2 text-sm text-slate-500">{isGoals ? "Set meaningful goals, track your progress, and turn plans into real progress." : "Keep important moments visible and act when the time is right."}</p></div>{error && <div className="state-row mb-4 text-rose-300">{error}</div>}{notice && <div className="state-row mb-4 text-emerald-300"><Check size={16} />{notice}</div>}{isGoals ? <Goals goals={data.goals} busy={busy} onCreate={(input) => run(() => createGoal(input), "Goal created.")} onComplete={(id) => run(() => completeGoal(id), "Goal completed.")} onDelete={(id) => run(() => deleteGoal(id), "Goal deleted.")} todayValue={todayValue} /> : <Reminders reminders={data.reminders} busy={busy} onCreate={(input) => run(() => createReminder(input), "Reminder created.")} onToggle={(id, value) => run(() => toggleReminder(id, value), "Reminder updated.")} onDelete={(id) => run(() => deleteReminder(id), "Reminder deleted.")} />}</main>;
}

function Goals({ goals, busy, onCreate, onComplete, onDelete, todayValue = today() }: { goals: PlanningData["goals"]; busy: boolean; onCreate: (input: { title: string; description: string; category: string; startDate: string; deadline: string }) => Promise<void>; onComplete: (id: string) => Promise<void>; onDelete: (id: string) => Promise<void>; todayValue?: string }) { const [open, setOpen] = useState(false); const [title, setTitle] = useState(""); const [deadline, setDeadline] = useState(todayValue); return <section className="glass-panel p-5"><Header icon={Target} title="Goals" action={<button className="primary-button" onClick={() => setOpen(!open)}><Plus size={15} /> Goal</button>} />{open && <form className="mb-4 grid gap-2 border-b border-white/10 pb-4 sm:grid-cols-2" onSubmit={async (event) => { event.preventDefault(); await onCreate({ title, description: "", category: "Personal", startDate: todayValue, deadline }); setTitle(""); setOpen(false); }}><input className="vault-input" placeholder="Goal title" value={title} onChange={(event) => setTitle(event.target.value)} required /><input className="vault-input" type="date" value={deadline} onChange={(event) => setDeadline(event.target.value)} required /><button className="primary-button" disabled={busy}>Create</button></form>}{goals.length ? <div className="space-y-2">{goals.map((goal) => <div className="goal-row" key={goal.id}><div className="goal-category">{goal.category.slice(0, 1)}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap gap-2"><strong className="text-sm text-slate-200">{goal.title}</strong><span className="goal-status goal-in-progress">{goal.status.toLowerCase().replace("_", " ")}</span></div><p className="mt-1 text-xs text-slate-500">{Math.round(goal.progress)}% · Due {goal.deadline}</p><div className="progress-track mt-2"><div className="progress-fill" style={{ width: `${goal.progress}%` }} /></div></div>{goal.status !== "COMPLETED" && <button className="icon-button" disabled={busy} aria-label={`Complete ${goal.title}`} onClick={() => void onComplete(goal.id)}><Check size={15} /></button>}<button className="icon-button text-rose-300" disabled={busy} aria-label={`Delete ${goal.title}`} onClick={() => void onDelete(goal.id)}><Trash2 size={14} /></button></div>)}</div> : <Empty text="No goals yet." />}</section>; }


function Reminders({ reminders, busy, onCreate, onToggle, onDelete }: { reminders: PlanningData["reminders"]; busy: boolean; onCreate: (input: { title: string; description: string; remindAt: string }) => Promise<void>; onToggle: (id: string, value: boolean) => Promise<void>; onDelete: (id: string) => Promise<void> }) { const [title, setTitle] = useState(""); const [remindAt, setRemindAt] = useState(""); return <section className="glass-panel p-5 xl:col-span-2"><Header icon={Bell} title="Reminders" action={null} /><form className="mb-4 grid gap-2 border-b border-white/10 pb-4 sm:grid-cols-[1fr_220px_auto]" onSubmit={async (event) => { event.preventDefault(); await onCreate({ title, description: "", remindAt }); setTitle(""); setRemindAt(""); }}><input className="vault-input" placeholder="Reminder title" value={title} onChange={(event) => setTitle(event.target.value)} required /><input className="vault-input" type="datetime-local" value={remindAt} onChange={(event) => setRemindAt(event.target.value)} required /><button className="primary-button" disabled={busy}><Plus size={15} /> Add</button></form>{reminders.length ? <div className="grid gap-2 md:grid-cols-2">{reminders.map((reminder) => <div className="state-row" key={reminder.id}><button className="text-cyan-300" disabled={busy} onClick={() => void onToggle(reminder.id, !reminder.completed)}>{reminder.completed ? <Check size={16} /> : <Circle size={16} />}</button><div className="min-w-0 flex-1"><p className={`text-sm ${reminder.completed ? "text-slate-600 line-through" : "text-slate-200"}`}>{reminder.title}</p><p className="text-xs text-slate-500">{new Date(reminder.remindAt).toLocaleString("en-US", { timeZone: "Asia/Dhaka", dateStyle: "medium", timeStyle: "short" })}</p></div><button className="icon-button text-rose-300" disabled={busy} aria-label={`Delete ${reminder.title}`} onClick={() => void onDelete(reminder.id)}><Trash2 size={14} /></button></div>)}</div> : <Empty text="No reminders yet." />}</section>; }

function Header({ icon: Icon, title, action }: { icon: typeof Target; title: string; action: React.ReactNode }) { return <div className="mb-4 flex items-center justify-between"><div className="flex items-center gap-2"><Icon size={17} className="text-cyan-300" /><h2 className="text-base font-medium text-white">{title}</h2></div>{action}</div>; }
function Empty({ text }: { text: string }) { return <div className="state-row justify-center text-xs">{text}</div>; }
